services:
  keep-frontend-dev:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    environment:
      - API_URL=http://keep-backend-dev:8080
    build:
      dockerfile: docker/Dockerfile.dev.ui
    volumes:
      - ./keep-ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - keep-backend-dev

  keep-backend-dev:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    build:
      dockerfile: docker/Dockerfile.dev.api
    volumes:
      - .:/app
      - ./state:/state
    depends_on:
      - keep-arq-redis

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common

  keep-arq-redis:
    extends:
      file: docker-compose.common.yml
      service: keep-arq-redis-common
